
const router = require("express").Router();

const Video = require("../models/Video");

const { protect, adminOnly } = require("../middleware/auth");

const {
  syncChannelToMongo,
  syncHealthUpdatePlaylist,
  searchVideosInMongo,
  generateAISummary,
} = require("../services/youtubeService");

// =====================================================
// GET /api/videos
// Example:
// /api/videos?playlistType=main
// /api/videos?playlistType=health_update
// /api/videos?category=Fitness&limit=20&page=1
// =====================================================

router.get("/", async (req, res) => {
  try {
    const {
      q,
      category,
      featured,
      playlistType,
      page = 1,
      limit = 20,
    } = req.query;

    const currentPage = Math.max(parseInt(page, 10) || 1, 1);

    // Prevent very large requests
    const pageLimit = Math.min(
      Math.max(parseInt(limit, 10) || 20, 1),
      50
    );

    const filter = {
      published: true,
    };

    // Search videos
    if (q && q.trim()) {
      const searchResults = await searchVideosInMongo(q.trim());

      return res.json({
        items: searchResults,
        total: searchResults.length,
        page: 1,
        pages: 1,
      });
    }

    // Filter by category
    if (category && category.trim()) {
      filter.category = category.trim();
    }

    // Filter featured videos
    if (featured === "true") {
      filter.featured = true;
    }

    // Filter playlist type
    if (playlistType) {
      const allowedPlaylistTypes = ["main", "health_update"];

      if (!allowedPlaylistTypes.includes(playlistType)) {
        return res.status(400).json({
          error:
            "Invalid playlistType. Use main or health_update.",
        });
      }

      filter.playlistType = playlistType;
    }

    const skip = (currentPage - 1) * pageLimit;

    const [total, items] = await Promise.all([
      Video.countDocuments(filter),

      Video.find(filter)
        .sort({
          order: 1,
          publishedAt: -1,
        })
        .skip(skip)
        .limit(pageLimit)
        .lean(),
    ]);

    res.json({
      success: true,
      items,
      total,
      page: currentPage,
      limit: pageLimit,
      pages: Math.ceil(total / pageLimit),
    });
  } catch (error) {
    console.error("Get videos error:", error);

    res.status(500).json({
      success: false,
      error: "Failed to fetch videos",
    });
  }
});

// =====================================================
// GET /api/videos/:id/summary
// AI summary - cached/generated by service
// =====================================================

router.get("/:id/summary", async (req, res) => {
  try {
    const video = await Video.findById(req.params.id);

    if (!video) {
      return res.status(404).json({
        success: false,
        error: "Video not found",
      });
    }

    const points = await generateAISummary(video);

    res.json({
      success: true,
      points,
    });
  } catch (error) {
    console.error("Generate summary error:", error);

    res.status(500).json({
      success: false,
      error: "Failed to generate AI summary",
    });
  }
});

// =====================================================
// POST /api/videos/sync
// Sync main channel + Health News Update playlist
// Admin only
// =====================================================

router.post("/sync", protect, adminOnly, async (req, res) => {
  try {
    const Settings = require("../models/Settings");

    const setting = await Settings.findOne({
      key: "youtubeChannelId",
    });

    const channelId =
      setting?.value || process.env.YOUTUBE_CHANNEL_ID;

    const healthUpdatePlaylistId =
      process.env.HEALTH_UPDATE_PLAYLIST_ID;

    if (!channelId) {
      return res.status(400).json({
        success: false,
        error: "YouTube channel ID is not configured",
      });
    }

    if (!healthUpdatePlaylistId) {
      return res.status(400).json({
        success: false,
        error:
          "Health Update playlist ID is not configured",
      });
    }

    const maxResults = Math.min(
      Math.max(Number(req.body.maxResults) || 50, 1),
      50
    );

    const [mainVideosCount, healthUpdateVideosCount] =
      await Promise.all([
        syncChannelToMongo(channelId, maxResults),

        syncHealthUpdatePlaylist(
          healthUpdatePlaylistId,
          maxResults
        ),
      ]);

    res.json({
      success: true,
      message: "YouTube videos synchronized successfully",
      mainVideosSynced: mainVideosCount,
      healthUpdateVideosSynced: healthUpdateVideosCount,
      totalSynced:
        mainVideosCount + healthUpdateVideosCount,
    });
  } catch (error) {
    console.error("Video synchronization error:", error);

    res.status(500).json({
      success: false,
      error: "Failed to synchronize YouTube videos",
    });
  }
});

// =====================================================
// PATCH /api/videos/:id
// Admin only
// Update featured, published, order, category, and tags
// =====================================================

router.patch("/:id", protect, adminOnly, async (req, res) => {
  try {
    const allowedFields = [
      "featured",
      "published",
      "order",
      "category",
      "tags",
    ];

    const update = {};

    allowedFields.forEach((field) => {
      if (req.body[field] !== undefined) {
        update[field] = req.body[field];
      }
    });

    if (Object.keys(update).length === 0) {
      return res.status(400).json({
        success: false,
        error: "No valid fields provided for update",
      });
    }

    const video = await Video.findByIdAndUpdate(
      req.params.id,
      update,
      {
        new: true,
        runValidators: true,
      }
    );

    if (!video) {
      return res.status(404).json({
        success: false,
        error: "Video not found",
      });
    }

    res.json({
      success: true,
      message: "Video updated successfully",
      video,
    });
  } catch (error) {
    console.error("Update video error:", error);

    res.status(500).json({
      success: false,
      error: "Failed to update video",
    });
  }
});

// =====================================================
// DELETE /api/videos/:id
// Admin only
// Deletes from database, not from YouTube
// =====================================================

router.delete("/:id", protect, adminOnly, async (req, res) => {
  try {
    const video = await Video.findByIdAndDelete(req.params.id);

    if (!video) {
      return res.status(404).json({
        success: false,
        error: "Video not found",
      });
    }

    res.json({
      success: true,
      message: "Video removed from database",
    });
  } catch (error) {
    console.error("Delete video error:", error);

    res.status(500).json({
      success: false,
      error: "Failed to delete video",
    });
  }
});

module.exports = router;